### ISSUE TITLE
Zenodo id for release

### ISSUE THREAD

**Issue by egull** [CQMP/Maxent#13]
@galexv, can you tie the recent release into Zenodo as a release with DOI?

**Comment by galexv** [comment]
Uploaded to Zenodo: 
[![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.51190.svg)](http://dx.doi.org/10.5281/zenodo.51190)

```html
    <a href="http://dx.doi.org/10.5281/zenodo.51190"><img src="https://zenodo.org/badge/doi/10.5281/zenodo.51190.svg" alt="10.5281/zenodo.51190"></a>
```

**Comment by galexv** [comment]
Uploaded to Zenodo: [![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.51221.svg)](http://dx.doi.org/10.5281/zenodo.51221)

```html
<a href="http://dx.doi.org/10.5281/zenodo.51221"><img src="https://zenodo.org/badge/doi/10.5281/zenodo.51221.svg" alt="10.5281/zenodo.51221"></a>
```
