### ISSUE TITLE
Macports BuildBot reports failure on ppc

### ISSUE THREAD

**Issue by egull** [CQMP/Maxent#16]
Status:       Failure
Build slave:  ports-10.5_ppc_legacy
Full logs:    https://build.macports.org/builders/ports-10.5_ppc_legacy-watcher/builds/925
Build reason: The SingleBranchScheduler scheduler named 'ports' triggered this build
Port list:    ALPSMaxent
Subport list:
	- ALPSMaxent
Variants:     None
Revision:     153205
Build time:   1:43:05
Committer:    g5pw@macports.org

Log from failed builds:
	Building 'ALPSMaxent' ... [ERROR]
	> maintainers: egull@umich.edu.

Broken ports:
	- ALPSMaxent

Responsible maintainers:
	- egull@umich.edu

Links to individual build jobs:
- ports-10.5_ppc_legacy-builder #7259
 https://build.macports.org/builders/ports-10.5_ppc_legacy-builder/builds/7259

-- 
Best regards,
MacPorts Buildbot
https://build.macports.org/

**Comment by egull** [comment]
...the build log states why: unrecognized command line option "-Wno-return-type-c-linkage"

This comes from the line 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2 -DNDEBUG -Wno-return-type-c-linkage")
...which is set in CMakeLists.txt

[  5%] Building CXX object CMakeFiles/libmaxent.dir/src/maxent_helper.cpp.o
/opt/local/bin/g++-apple-4.2    -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_science_ALPSMaxent/ALPSMaxent/work/build/config -isystem /opt/local/include -I/opt/local/include/eigen3  -pipe -Os  -O2 -DNDEBUG -Wno-return-type-c-linkage -msse2 -DNDEBUG -arch ppc -mmacosx-version-min=10.5   -o CMakeFiles/libmaxent.dir/src/maxent_helper.cpp.o -c /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_science_ALPSMaxent/ALPSMaxent/work/Maxent-1.0/src/maxent_helper.cpp
cc1plus: error: unrecognized command line option "-Wno-return-type-c-linkage"

**Comment by ryanlevy** [comment]
The flag is in there from commit 0ac21dbea4b06b81468d637f27368481c6903610
"disabling boost warnings for c type linkage"
Should we just remove it for older Apple gcc (<5)?

**Comment by egull** [comment]
Yes, I think so. I just found it there too... Do you want to do it? @galexv should then do a release with the right auxiliary files and commit to Zenodo, and I'll update their macports file.

**Comment by ryanlevy** [comment]
Alternatively, we add `CHECK_CXX_COMPILER_FLAG(-Wno-return-type-c-linkage SUPPORTS_FLAG)` as a more universal check. I'll commit that in and make sure the lack of the flag doesn't cause anything more than inconvenience.

**Comment by ryanlevy** [comment]
Removing the flag doesn't present a problem for GCC 5, clang 7 on OSX 10.11 and GCC 4.9 and 5 on Ubuntu 15.04. We'll stick with the cmake check for flag compatibility
