### ISSUE TITLE
SIGMA1 and SIGMA2 are not defined for double gaussian

### ISSUE THREAD

**Issue by egull** [CQMP/Maxent#17]
when trying to use two gaussians as a default model, the code complains:

Using sum of two Gaussians default model
Caught Exception Dynamic exception type: alps::params_ns::option_type::uninitialized_value
std::exception::what: Option 'SIGMA1': Attempt to access non-existing key 'SIGMA1'

....and indeed they don't show up in the help:
  --SHIFT1 arg (=0)                  for Two Gaussians model
  --SHIFT2 arg                       for Two Gaussians model
  --SIGMA arg                        stddev - For Gaussian models
  --SIGMA_0 arg                      G error input for param file entry
  --SPREAD arg (=4)                  spread for quadratic grid

**Comment by ryanlevy** [comment]
Apparently ALPSCore won't throw this error when you define parameters programmatically, as a test for this was meant to be covered in `default_modelTest.cpp`. I'll add the proper definitions.
