### ISSUE TITLE
error while loading shared libraries: libgsl.so.23 on Ubuntu 12

### ISSUE THREAD

**Issue by pbakalov** [CQMP/Maxent#30]
All tests fail with this error:
`./test/default_modelTest: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory`

One can fix this by doing:
`$ LD_LIBRARY_PATH=/usr/local/lib/`
`$ export LD_LIBRARY_PATH`

(or add something in that spirit to one's ~/.bashrc).

This doesn't seem to be a very neat workaround + probably it's not how things are intended to work.

Where could the problem be and is there another way to fix that? 

P.S. The output of the configuration can be found [here](https://gist.github.com/pbakalov/9b58b02d111c0864ef80221658b1c503).

**Comment by ryanlevy** [comment]
The [GSL manual](https://www.gnu.org/software/gsl/manual/html_node/Shared-Libraries.html) actually gives that as the solution. 
For now that'll be a work around, but I think we can force cmake to load the full path and not rely on `LD_LIBRARY_PATH`

**Comment by ryanlevy** [comment]
[After some digging](https://stackoverflow.com/questions/33165270/force-cmake-to-use-the-full-library-path), it appears this is because in Ubuntu the GSL install path is an implicit search path. No matter what I've tried, I can't seem to get the `RPATH` for GSL to link under Ubuntu, but it is working for OSX...

**Comment by egull** [comment]
OK. So what should we do? Would specifying -DGSL_ROOT_DIR=... help and enforce the path?

**Comment by pbakalov** [comment]
If this is the solution in the GSL manual, maybe it's not such a sloppy workaround, after all.

I guess it's good enough for me. Many thanks!

**Comment by egull** [comment]
OK. Closing this despite not actually having a decent and useful solution.
