### ISSUE TITLE
Compile Fail: alps/utilities/remove_extensions.hpp: No such file or directory

### ISSUE THREAD

**Issue by DalInar** [CQMP/Maxent#31]
Hi all,

Not sure if this is an ALPSCore or MaxEnt issue, but I've run into the following error when compiling MaxEnt:

```
/u/home/oryx/ALPSCore_Joe/Maxent/src/maxent.cpp:21:48: fatal error: alps/utilities/remove_extensions.hpp: No such file or directory
 #include <alps/utilities/remove_extensions.hpp>
```
And indeed, that header file does not exist in the current version of ALPSCore (or at least, it's not in the version I pulled a few days ago, and does not seem to be in the repo now.)  So I'm guessing that ALPSCore was refactored recently and this header was dropped...

**Comment by ryanlevy** [comment]
Try doing a `git pull`, I fixed this bug in the [latest commit](https://github.com/CQMP/Maxent/commit/0defb322e297e08f6a62027be05953bfc55d7c82) on both the master and GPLv3 branches

**Comment by DalInar** [comment]
Yay! Thanks Ryan.
