### ISSUE TITLE
Test Passed but can't run examples

### ISSUE THREAD

**Issue by dxka8998** [CQMP/Maxent#50]
After I enter
$ ./maxent /Users/###/Maxent-1.1.1/examples/U0/in_tau.param

it shows:

Caught Exception Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::invalid_argument> >
std::exception::what: could not open data text file: Gtau. data should be specified in parameter DATA

**Comment by egull** [comment]
Did you check the location of the data file Gtau? Is it in the current
directory under Gtau?
